{"name":"DateDimensionBI","description":"Date reference table which can be used in PowerBI reports","version":"1.0","culture":"en-AU","modifiedTime":"2024-01-09T06:32:22.9823338+00:00","ppdf:outputFileFormat":"csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"skipAutomaticHeaderAndTypeDetection":false,"queriesMetadata":{"DateDimensionBI":{"queryId":"0c6aa5a7-7fd2-4011-8f1a-df5ecc3dc8cd","queryName":"DateDimensionBI","loadEnabled":true}},"document":"section Section1;\r\nshared DateDimensionBI = let\r\n  Source = {Number.From(#date(2016,1,1)) .. Number.From(#date(2026,12,31))},\r\n  #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\", {{\"Column1\", type date}}),\r\n  #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\", {{\"Column1\", \"Date\"}}),\r\n  #\"Added Year\" = Table.AddColumn(#\"Renamed Columns\", \"Year\", each Date.Year([Date]), Int64.Type),\r\n  // Year Number (2021, 2022)\r\n  #\"Added Start of Year\" = Table.AddColumn(#\"Added Year\", \"Start of Year\", each Date.StartOfYear([Date]), type date),\r\n  // #\"Start of Year Date (01-01-2021)\r\n  #\"Added End of Year\" = Table.AddColumn(#\"Added Start of Year\", \"End of Year\", each Date.EndOfYear([Date]), type date),\r\n  // #\"End of Year Date (31-12-2021)\r\n  #\"Added Month Number\" = Table.AddColumn(#\"Added End of Year\", \"Month Number\", each Date.Month([Date]), Int64.Type),\r\n  // Month Number\" (1-12)\r\n  #\"Added Month Name\" = Table.AddColumn(#\"Added Month Number\", \"Month Name\", each Date.MonthName([Date])),\r\n  // Month Name (January - December)\r\n  #\"Added Month Start Date\" = Table.AddColumn(#\"Added Month Name\", \"Month Start Date\", each Date.StartOfMonth([Date]), type date),\r\n  // Month Start Date (01-02-2021)\r\n  #\"Added Month End Date\" = Table.AddColumn(#\"Added Month Start Date\", \"Month End Date\", each Date.EndOfMonth([Date]), type date),\r\n  // Month End Date (28-02-2021)\r\n  #\"Added Days in Month\" = Table.AddColumn(#\"Added Month End Date\", \"Days in Month\", each Date.DaysInMonth([Date]), Int64.Type),\r\n  // Days in Month (31, 28, 30 )\r\n  #\"Added Quarter Number\" = Table.AddColumn(#\"Added Days in Month\", \"Quarter Number\", each Date.QuarterOfYear([Date]), Int64.Type),\r\n  // Quarter Number (1-4)\r\n  #\"Added Quarter Start Date\" = Table.AddColumn(#\"Added Quarter Number\", \"Quarter Start Date\", each Date.StartOfQuarter([Date]), type date),\r\n  // Quarter Start Date (01-04-2021)\r\n  #\"Added Quarter End Date\" = Table.AddColumn(#\"Added Quarter Start Date\", \"Quarter End Date\", each Date.EndOfQuarter([Date]), type date),\r\n  // Quarter End Date (31-03-2021)\r\n  #\"Added Week Number of Year\" = Table.AddColumn(#\"Added Quarter End Date\", \"Week Number of Year\", each Date.WeekOfYear([Date]), Int64.Type),\r\n  // Week Number of Year (1-53)\r\n  #\"Added Week Number of Month\" = Table.AddColumn(#\"Added Week Number of Year\", \"Week Number of Month\", each Date.WeekOfMonth([Date]), Int64.Type),\r\n  // Week Number of Month (1-5 )\r\n  #\"Added Week Start Date\" = Table.AddColumn(#\"Added Week Number of Month\", \"Week Start Date\", each Date.StartOfWeek([Date]), type date),\r\n  // Week Start Date (18-01-2021)\r\n  #\"Added Week End Date\" = Table.AddColumn(#\"Added Week Start Date\", \"Week End Date\", each Date.EndOfWeek([Date]), type date),\r\n  // Week End Date (24-01-2021)\r\n  #\"Added Day of Month\" = Table.AddColumn(#\"Added Week End Date\", \"Day of Month\", each Date.Day([Date]), Int64.Type),\r\n  // Day of Month (1-31 )\r\n  #\"Added Day of Week\" = Table.AddColumn(#\"Added Day of Month\", \"Day of Week\", each Date.DayOfWeek([Date]), Int64.Type),\r\n  // Day of Week (1-7)\r\n  #\"Added Day of Year\" = Table.AddColumn(#\"Added Day of Week\", \"Day of Year\", each Date.DayOfYear([Date]), Int64.Type),\r\n  // Day of Year (1-365)\r\n  #\"Added Day Name\" = Table.AddColumn(#\"Added Day of Year\", \"Day Name\", each Date.DayOfWeekName([Date])),\r\n  #\"Added t-90\" = Table.AddColumn(#\"Added Day Name\", \"t-90\", each ([Date] >= Date.AddDays(DateTime.Date(DateTime.LocalNow()), - 90)) and [Date] <= DateTime.Date(DateTime.LocalNow())),\r\n  #\"Added isFuture\" = Table.AddColumn(#\"Added t-90\", \"isFuture\", each [Date] > DateTime.Date(DateTime.LocalNow())),\r\n  #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added isFuture\", {{\"t-90\", type logical}, {\"isFuture\", type logical}}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Changed Type1\", {{\"Month Name\", type text}, {\"Day Name\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Month Name\", null}, {\"Day Name\", null}})\r\nin\r\n  #\"Replace errors\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"DateDimensionBI","description":"Date reference table you can use in PowerBI reports","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"DateDimensionBI.csv"},"attributes":[{"name":"Date","dataType":"date"},{"name":"Year","dataType":"int64"},{"name":"Start of Year","dataType":"date"},{"name":"End of Year","dataType":"date"},{"name":"Month Number","dataType":"int64"},{"name":"Month Name","dataType":"string"},{"name":"Month Start Date","dataType":"date"},{"name":"Month End Date","dataType":"date"},{"name":"Days in Month","dataType":"int64"},{"name":"Quarter Number","dataType":"int64"},{"name":"Quarter Start Date","dataType":"date"},{"name":"Quarter End Date","dataType":"date"},{"name":"Week Number of Year","dataType":"int64"},{"name":"Week Number of Month","dataType":"int64"},{"name":"Week Start Date","dataType":"date"},{"name":"Week End Date","dataType":"date"},{"name":"Day of Month","dataType":"int64"},{"name":"Day of Week","dataType":"int64"},{"name":"Day of Year","dataType":"int64"},{"name":"Day Name","dataType":"string"},{"name":"t-90","dataType":"boolean"},{"name":"isFuture","dataType":"boolean"}],"partitions":[{"name":"Part001","refreshTime":"2024-01-09T06:34:54.3865379+00:00","location":"https://wabiaussoueascdsap1.blob.core.windows.net:443/5ca60b03-bbce-4568-84c0-11923c3e693e/DateDimensionBI.csv?snapshot=2024-01-09T06%3A34%3A54.3837959Z"}]}]}